name: testgit
description: ''
version: 0.0.1
author: suryansh@adobe.com
language: python
buildSystem: wheel
pipelines:
  pipelines/testgitpipe:
    name: testgitpipe
    description: ''
    author: suryansh@adobe.com
    mode: batch
    language: python
    createdAt: '2023-02-24 08:37:29'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
